version: '3.9'
services:
    postgress:  
        image: postgres:latest
        container_name: somecontainerName
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        ports:
          - '5432:5432'
        volumes:
          - data:/var/lib/postgresql/data
volumes:
    data: